services:
  redis:
    image: redis:7-alpine
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - ./deploy/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - ./docker/shared/redis:/data
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ES_VERSION}
    healthcheck:
      test: curl -u elastic:elastic -s -f elasticsearch:9200/_cat/health >/dev/null || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "127.0.0.1:9200:9200"
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    deploy:
      resources:
        limits:
          memory: 1g
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./deploy/elasticsearch.conf.d/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties
      - ./deploy/elasticsearch.conf.d/elasticsearch-primary.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - esdata:/usr/share/elasticsearch/data
  db:
    image: postgis/postgis:15-3.3
    volumes:
      - ./docker/pgdata:/var/lib/postgresql/data
      - ./build/secrets/db_password:/run/secrets/db_password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 30s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
  vite:
    build: frontend
    image: comses/comsesnet-vite
    volumes:
      - /code/node_modules
      - ./docker/shared:/shared
      - ./build/secrets/config.ini:/run/secrets/config.ini
  server:
    build: django
    image: comses/server
    volumes:
      - ./build/secrets:/run/secrets
      - ./deploy/elasticsearch.conf.d:/etc/elasticsearch
      - ./docker/shared:/shared
    depends_on:
      db:
        condition: service_healthy
      elasticsearch:
        condition: service_started
      redis:
        condition: service_started
      vite:
        condition: service_started
    environment:
      CLEAN_DATABASE: "false"
volumes:
  esdata:
    driver: local
