services:
  redis:
    image: redis:7-alpine
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - ./deploy/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - ./docker/shared/redis:/data
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ES_VERSION}
    healthcheck:
      test: curl -u elastic:elastic -s -f elasticsearch:9200/_cat/health >/dev/null || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "127.0.0.1:9200:9200"
    environment:
      - node.name=elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    deploy:
      resources:
        limits:
          memory: 1g
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./deploy/elasticsearch.conf.d/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties
      - esdata:/usr/share/elasticsearch/data
  db:
    image: postgis/postgis:16-3.5
    secrets:
      - db_password
    volumes:
      - ./docker/pgdata:/var/lib/postgresql/data
      - ./build/secrets/db_password:/run/secrets/db_password
      - ./docker/shared:/shared
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 30s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
  vite:
    build: frontend
    image: comses/vite
    volumes:
      - /code/node_modules
      - ./docker/shared:/shared
      - ./build/secrets/config.ini:/run/secrets/config.ini
  server:
    build: django
    image: comses/server
    secrets:
      - datacite_api_password
      - db_password
      - discourse_api_key
      - discourse_sso_secret
      - django_secret_key
      - github_client_secret
      - orcid_client_secret
      - hcaptcha_secret
      - mail_api_key
      - llm_spam_check_api_key
    volumes:
      - ./deploy/elasticsearch.conf.d:/etc/elasticsearch
      - ./docker/shared:/shared
      - ./.env:/etc/environment
    depends_on:
      db:
        condition: service_healthy
      elasticsearch:
        condition: service_started
      redis:
        condition: service_started
      vite:
        condition: service_started
    env_file:
      - ./.env

secrets:
  datacite_api_password:
    file: ./build/secrets/datacite_api_password
  db_password:
    file: ./build/secrets/db_password
  discourse_api_key:
    file: ./build/secrets/discourse_api_key
  discourse_sso_secret:
    file: ./build/secrets/discourse_sso_secret
  django_secret_key:
    file: ./build/secrets/django_secret_key
  github_client_secret:
    file: ./build/secrets/github_client_secret
  hcaptcha_secret:
    file: ./build/secrets/hcaptcha_secret
  mail_api_key:
    file: ./build/secrets/mail_api_key
  orcid_client_secret:
    file: ./build/secrets/orcid_client_secret
  llm_spam_check_api_key:
    file: ./build/secrets/llm_spam_check_api_key

volumes:
  esdata:
    driver: local
