services:
  elasticsearch:
    environment:
      - discovery.type=single-node
  vite:
    ports:
      - "127.0.0.1:5173:5173"
    volumes:
      - ./frontend:/code
    environment:
      NODE_ENV: "development"
  server:
    build:
      args:
        UBUNTU_MIRROR: "${UBUNTU_MIRROR}"
    image: comses/server:dev
    volumes:
      - ./django:/code
      - ./docs:/docs
    environment:
      DJANGO_SETTINGS_MODULE: "core.settings.dev"
    ports:
      - "127.0.0.1:8000:8000"
