services:
  js:
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - ./frontend:/code
    environment:
      NODE_ENV: "development"
  vite:
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
      - ./frontend-vue3:/code
    environment:
      NODE_ENV: "development"
  server:
    image: comses/server:dev
    volumes:
      - ./django:/code
      - ./docs:/docs
    environment:
      DJANGO_SETTINGS_MODULE: "core.settings.dev"
    ports:
      - "127.0.0.1:8000:8000"
