services:
  db:
    image: alpine # disable the normal db container
    command: tail -f /dev/null
    healthcheck:
      disable: true
  elasticsearch:
    environment:
      - discovery.type=single-node
  e2edb:
    image: postgis/postgis:16-3.5
    secrets:
      - db_password # re-using the same db password
    volumes:
      - ./build/secrets/db_password:/run/secrets/db_password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 30s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
  vite:
    command: ["npm", "run", "build"]
    ports:
      - "127.0.0.1:5173:5173"
    environment:
      NODE_ENV: "e2e"
    volumes:
      - ./frontend:/code
  server:
    build:
      args:
        RUN_SCRIPT: ./deploy/dev.sh
    depends_on:
      db:
        condition: service_started
      e2edb:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
      redis:
        condition: service_started
      vite:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "127.0.0.1:8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: "core.settings.e2e"
