# Generated by Django 2.0.4 on 2018-04-07 00:21

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="journalsnippetplacement",
            options={
                "ordering": ("journal__name",),
                "verbose_name": "journal placement",
                "verbose_name_plural": "journal placements",
            },
        ),
        migrations.AlterModelOptions(
            name="platformsnippetplacement",
            options={
                "ordering": ("platform__name",),
                "verbose_name": "platform placement",
                "verbose_name_plural": "platform placements",
            },
        ),
        migrations.RemoveField(
            model_name="faqentryplacement",
            name="sort_order",
        ),
        migrations.RemoveField(
            model_name="journalsnippetplacement",
            name="sort_order",
        ),
        migrations.RemoveField(
            model_name="platformsnippetplacement",
            name="sort_order",
        ),
    ]
