# Generated by Django 2.0.4 on 2018-04-22 07:37

from django.db import migrations


def rerender_all_journal_descriptions(apps, schema_editor):
    Journal = apps.get_model('home', 'Journal')
    for j in Journal.objects.iterator():
        j.description = j.description.raw
        j.save()

class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20180421_0144'),
    ]

    operations = [
        migrations.RunPython(rerender_all_journal_descriptions),
    ]
