# Generated by Django 2.1.2 on 2018-10-30 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_conferencesubmission"),
    ]

    operations = [
        migrations.AddField(
            model_name="peopleentryplacement",
            name="term",
            field=models.CharField(
                blank=True,
                help_text="The term for a given board member (e.g., 2016-2018)",
                max_length=32,
            ),
        ),
    ]
