# Generated by Django 2.1.7 on 2019-02-19 21:10

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0010_people_page_description_markdown"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journal",
            name="description",
            field=core.fields.MarkdownField(blank=True, rendered_field=True),
        ),
        migrations.AlterField(
            model_name="markdownpage",
            name="description",
            field=core.fields.MarkdownField(
                blank=True,
                help_text="Markdown-enabled summary text placed below the heading and title.",
                max_length=1024,
                rendered_field=True,
            ),
        ),
    ]
