# Generated by Django 3.2.16 on 2022-11-10 20:40

import core.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0069_log_entry_jsonfield'),
        ('home', '0014_add_education_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorialDetailPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('heading', models.CharField(blank=True, help_text='Large heading text placed on the blue background introduction header', max_length=128)),
                ('template', models.CharField(default='home/markdown_page.jinja', max_length=128)),
                ('post_date', models.DateField(default=django.utils.timezone.now, verbose_name='Post date')),
                ('description', core.fields.MarkdownField(blank=True, help_text='Markdown-enabled summary text placed below the heading and title.', max_length=1024, rendered_field=True)),
                ('description_markup_type', models.CharField(choices=[('', '--'), ('markdown', 'markdown'), ('html', 'html'), ('plain', 'plain'), ('', '')], default='markdown', max_length=30)),
                ('body', core.fields.MarkdownField(blank=True, help_text='Markdown-enabled main content pane for this page.', rendered_field=True)),
                ('_description_rendered', models.TextField(editable=False)),
                ('body_markup_type', models.CharField(choices=[('', '--'), ('markdown', 'markdown'), ('html', 'html'), ('plain', 'plain'), ('', '')], default='markdown', max_length=30)),
                ('jumbotron', models.BooleanField(default=True, help_text='Mark as true if this page should display its title and description in a jumbotron')),
                ('_body_rendered', models.TextField(editable=False)),
            ],
            options={
                'abstract': False,
            },
            bases=(home.models.NavigationMixin, 'wagtailcore.page'),
        ),
    ]
