# Generated by Django 3.2.16 on 2022-11-10 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_tutorial_detail_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorialdetailpage',
            name='template',
            field=models.CharField(default='home/tutorial.jinja', max_length=128),
        ),
    ]
