# Generated by Django 3.2.18 on 2023-03-20 22:52

from django.db import migrations, models
import wagtail.search.index


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_peopleentryplacement_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigestArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_published', models.IntegerField()),
                ('season', models.IntegerField(choices=[(1, 'Spring'), (2, 'Summer'), (3, 'Fall'), (4, 'Winter')])),
                ('volume', models.IntegerField()),
                ('number', models.IntegerField()),
                ('static_path', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'ordering': ['-volume', '-number'],
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
    ]
