# Generated by Django 4.2.15 on 2024-09-23 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0018_alter_journaltag_tag_alter_tutorialtag_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutorialcard",
            name="category",
            field=models.CharField(
                choices=[
                    ("in-house", "CoMSES"),
                    ("partner", "Partners"),
                    ("community", "Open Science Community"),
                ],
                default="in-house",
                max_length=32,
            ),
        ),
    ]
