# Generated by Django 4.2.21 on 2025-06-26 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    def delete_existing_digests(apps, schema_editor):
        ComsesDigest = apps.get_model("home", "ComsesDigest")
        ComsesDigest.objects.all().delete()

    dependencies = [
        ("home", "0019_tutorialcard_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comsesdigest",
            name="contributors",
        ),
        migrations.RemoveField(
            model_name="comsesdigest",
            name="season",
        ),
        migrations.RemoveField(
            model_name="comsesdigest",
            name="static_path",
        ),
        migrations.AddField(
            model_name="comsesdigest",
            name="title",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="comsesdigest",
            name="url",
            field=models.CharField(default="", max_length=256),
            preserve_default=False,
        ),
        migrations.RunPython(migrations.RunPython.noop, delete_existing_digests),
    ]
