# Generated by Django 4.2.21 on 2025-06-26 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0019_tutorialcard_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comsesdigest",
            name="season",
        ),
        migrations.RemoveField(
            model_name="comsesdigest",
            name="static_path",
        ),
        migrations.AddField(
            model_name="comsesdigest",
            name="title",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="comsesdigest",
            name="url",
            field=models.CharField(default="", max_length=256, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="comsesdigest",
            name="doi",
            field=models.CharField(blank=True, default="", max_length=128, unique=True),
            preserve_default=False,
        ),
    ]
