# Generated by Django 4.2.21 on 2025-06-10 20:25

from django.conf import settings
from django.db import migrations, models

from core.fields import MarkdownField

def set_default_content(apps, schema_editor):
    LandingPage = apps.get_model("home", "LandingPage")
    
    default_library_blurb = """
Preserve the [digital artifacts and context](https://datascience.nih.gov/tools-and-analytics/best-practices-for-sharing-research-software-faq) that published research findings depend on in an open digital repository that supports the [FAIR4RS Principles](https://doi.org/10.15497/RDA00068) and good practices for [software citation](https://peerj.com/articles/cs-86) and reuse.

[Adopt good open science practices](/resources/guides-to-good-practice) for developing, documenting, and publishing your computational models and [submit your models for peer review for a DOI](/reviews).
    """.strip()
    
    default_community_blurb = f"""
Stay informed about upcoming conferences, workshops, and meetings. Find career opportunities or share relevant jobs or events with our international community.

Use our [community forums]({settings.DISCOURSE_BASE_URL}) to get help, inquire about a specific model release, share insights, and connect with fellow modelers and researchers.
    """.strip()
    
    default_resources_blurb = """
We maintain these community curated resources to help both new and experienced computational modelers adopt [good practices](/education/responsible-practices) for research data management and improve the discoverability, reusability, and reproducibility of their computational models.

[**Education and training <i class="fas fa-chevron-right ms-1"></i>**](/education)

[**Modeling frameworks <i class="fas fa-chevron-right ms-1"></i>**](/resources/frameworks)

[**Journals <i class="fas fa-chevron-right ms-1"></i>**](/resources/journals)

[**Standards <i class="fas fa-chevron-right ms-1"></i>**](/resources/standards)
    """.strip()
    
    for page in LandingPage.objects.all():
        # Update title
        page.title = "The Network for Computational Modeling in the Social and Ecological Sciences"
        
        # Set blurb content if empty
        page.community_blurb = default_community_blurb
        page.library_blurb = default_library_blurb
        page.resources_blurb = default_resources_blurb
        page.save()


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0019_tutorialcard_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="landingpage",
            name="community_statement",
            field=models.TextField(default=""),
        ),
        migrations.RemoveField(
            model_name="landingpage",
            name="community_statement",
        ),
        migrations.AddField(
            model_name="landingpage",
            name="_community_blurb_rendered",
            field=models.TextField(default="", editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="landingpage",
            name="_library_blurb_rendered",
            field=models.TextField(default="", editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="landingpage",
            name="_resources_blurb_rendered",
            field=models.TextField(default="", editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="landingpage",
            name="community_blurb",
            field=MarkdownField(
                blank=True, max_length=1024, rendered_field=True
            ),
        ),
        migrations.AddField(
            model_name="landingpage",
            name="community_blurb_markup_type",
            field=models.CharField(
                choices=[
                    ("", "--"),
                    ("markdown", "markdown"),
                    ("html", "html"),
                    ("plain", "plain"),
                    ("", ""),
                ],
                default="markdown",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="landingpage",
            name="community_title",
            field=models.CharField(
                default="A community of researchers", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="landingpage",
            name="library_blurb",
            field=MarkdownField(
                blank=True, max_length=1024, rendered_field=True
            ),
        ),
        migrations.AddField(
            model_name="landingpage",
            name="library_blurb_markup_type",
            field=models.CharField(
                choices=[
                    ("", "--"),
                    ("markdown", "markdown"),
                    ("html", "html"),
                    ("plain", "plain"),
                    ("", ""),
                ],
                default="markdown",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="landingpage",
            name="library_title",
            field=models.CharField(default="The CoMSES Model Library", max_length=255),
        ),
        migrations.AddField(
            model_name="landingpage",
            name="resources_blurb",
            field=MarkdownField(
                blank=True, max_length=1024, rendered_field=True
            ),
        ),
        migrations.AddField(
            model_name="landingpage",
            name="resources_blurb_markup_type",
            field=models.CharField(
                choices=[
                    ("", "--"),
                    ("markdown", "markdown"),
                    ("html", "html"),
                    ("plain", "plain"),
                    ("", ""),
                ],
                default="markdown",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="landingpage",
            name="resources_title",
            field=models.CharField(default="Resources for modeling", max_length=255),
        ),
        # Set default title and content for the new fields
        migrations.RunPython(
            set_default_content,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="featuredcontentitem",
            name="caption",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
