# Generated by Django 4.2.22 on 2025-06-28 21:01

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0020_remove_comsesdigest_contributors_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="landingpage",
            name="community_statement",
        ),
        migrations.AddField(
            model_name="landingpage",
            name="_community_blurb_rendered",
            field=models.TextField(default="", editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="landingpage",
            name="_library_blurb_rendered",
            field=models.TextField(default="", editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="landingpage",
            name="_resources_blurb_rendered",
            field=models.TextField(default="", editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="landingpage",
            name="community_blurb",
            field=core.fields.MarkdownField(
                blank=True, max_length=1024, rendered_field=True
            ),
        ),
        migrations.AddField(
            model_name="landingpage",
            name="community_blurb_markup_type",
            field=models.CharField(
                choices=[
                    ("", "--"),
                    ("markdown", "markdown"),
                    ("html", "html"),
                    ("plain", "plain"),
                    ("", ""),
                ],
                default="markdown",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="landingpage",
            name="community_title",
            field=models.CharField(
                default="A community of researchers", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="landingpage",
            name="library_blurb",
            field=core.fields.MarkdownField(
                blank=True, max_length=1024, rendered_field=True
            ),
        ),
        migrations.AddField(
            model_name="landingpage",
            name="library_blurb_markup_type",
            field=models.CharField(
                choices=[
                    ("", "--"),
                    ("markdown", "markdown"),
                    ("html", "html"),
                    ("plain", "plain"),
                    ("", ""),
                ],
                default="markdown",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="landingpage",
            name="library_title",
            field=models.CharField(default="The CoMSES Model Library", max_length=255),
        ),
        migrations.AddField(
            model_name="landingpage",
            name="resources_blurb",
            field=core.fields.MarkdownField(
                blank=True, max_length=1024, rendered_field=True
            ),
        ),
        migrations.AddField(
            model_name="landingpage",
            name="resources_blurb_markup_type",
            field=models.CharField(
                choices=[
                    ("", "--"),
                    ("markdown", "markdown"),
                    ("html", "html"),
                    ("plain", "plain"),
                    ("", ""),
                ],
                default="markdown",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="landingpage",
            name="resources_title",
            field=models.CharField(default="Resources for modeling", max_length=255),
        ),
        migrations.AlterField(
            model_name="featuredcontentitem",
            name="caption",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
