# Generated by Django 3.2.20 on 2023-07-13 19:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ArchivedQueryHits",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("query_string", models.CharField(max_length=255)),
                ("hits", models.IntegerField()),
                ("last_updated", models.DateField()),
            ],
        ),
    ]
