# Generated by Django 2.1.2 on 2018-10-25 03:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_platform_description_20180520_0549"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={},
        ),
        migrations.AlterModelOptions(
            name="job",
            options={},
        ),
    ]
