# Generated by Django 2.1.2 on 2018-11-01 21:04

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_auto_20181025_0352"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memberprofile",
            name="bio",
            field=core.fields.MarkdownField(
                blank=True, help_text="Brief bio", max_length=2048, rendered_field=True
            ),
        ),
        migrations.AlterField(
            model_name="memberprofile",
            name="research_interests",
            field=core.fields.MarkdownField(
                blank=True, max_length=2048, rendered_field=True
            ),
        ),
    ]
