# Generated by Django 2.2.11 on 2020-04-03 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_banner_message_markdown"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="mailchimp_digest_archive_url",
            field=models.URLField(
                blank=True, help_text="Mailchimp Digest Campaign Archive URL"
            ),
        ),
    ]
