# Generated by Django 3.0.11 on 2021-02-02 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_sitesettings_banner_message_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='short_uuid',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
    ]
