# Generated by Django 3.1.7 on 2021-03-19 20:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_add_member_profile_short_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memberprofile",
            name="affiliations",
            field=models.JSONField(
                default=list, help_text="JSON-LD list of affiliated institutions"
            ),
        ),
    ]
