# Generated by Django 3.1.10 on 2021-05-11 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_json_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='ror_id',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='platform',
            name='repository_url',
            field=models.URLField(blank=True),
        ),
    ]
