# Generated by Django 3.2.12 on 2022-06-10 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_ror_id_and_platform_repository_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="Industry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("user_entered", models.BooleanField(default=False)),
                ("description", models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name="memberprofile",
            name="industry",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.industry",
            ),
        ),
    ]
