# Generated by Django 3.2.15 on 2022-09-21 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_memberprofile_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='acronym',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
