# Generated by Django 4.2.11 on 2024-05-20 22:15

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0020_alter_eventtag_tag_alter_jobtag_tag_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="is_marked_spam",
            field=models.BooleanField(
                default=False,
                help_text="cached boolean representation of spam_moderation for search indexing",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="is_marked_spam",
            field=models.BooleanField(
                default=False,
                help_text="cached boolean representation of spam_moderation for search indexing",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="submitter",
            field=models.ForeignKey(
                blank=True,
                on_delete=models.SET(core.models.get_sentinel_user),
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="SpamModeration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unreviewed", "Unreviewed"),
                            ("spam", "Confirmed spam"),
                            ("not_spam", "Confirmed not spam"),
                        ],
                        default="unreviewed",
                        max_length=32,
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes left by the reviewer",
                        null=True,
                    ),
                ),
                (
                    "detection_method",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "detection_details",
                    models.JSONField(
                        default=dict,
                        help_text="Extra context from the detection method, e.g. NLP results, elapsed time",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.SET(core.models.get_sentinel_user),
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="event",
            name="spam_moderation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.spammoderation",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="spam_moderation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.spammoderation",
            ),
        ),
    ]
