# Generated by Django 4.2.11 on 2024-05-10 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0020_alter_eventtag_tag_alter_jobtag_tag_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="is_marked_spam",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="job",
            name="is_marked_spam",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="SpamContent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unreviewed", "Unreviewed"),
                            ("confirmed", "Confirmed"),
                            ("rejected", "Rejected"),
                        ],
                        default="unreviewed",
                        max_length=32,
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("review_notes", models.TextField(blank=True, null=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="event",
            name="spam_content",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.spamcontent",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="spam_content",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.spamcontent",
            ),
        ),
    ]
