# Generated by Django 4.2.17 on 2025-02-18 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_add_spam_moderation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="socialmediasettings",
            name="twitter_account",
        ),
        migrations.AddField(
            model_name="socialmediasettings",
            name="social_account",
            field=models.CharField(
                blank=True,
                default="comses",
                help_text="CoMSES Net official socials account username (assumed focus on a single platform)",
                max_length=128,
            ),
        ),
    ]
