# Generated by Django 4.2.16 on 2024-12-16 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_add_spam_moderation"),
    ]

    operations = [
        migrations.AddField(
            model_name="memberprofile",
            name="is_marked_spam",
            field=models.BooleanField(
                default=False,
                help_text="cached boolean representation of spam_moderation for search indexing",
            ),
        ),
        migrations.AddField(
            model_name="memberprofile",
            name="spam_moderation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.spammoderation",
            ),
        ),
        migrations.AlterField(
            model_name="spammoderation",
            name="status",
            field=models.CharField(
                choices=[
                    ("spam", "Confirmed spam"),
                    ("not_spam", "Confirmed not spam"),
                    ("scheduled_for_check", "Scheduled for check by LLM"),
                    ("spam_likely", "Automatically marked as spam"),
                    ("not_spam_likely", "Automatically marked as not spam"),
                ],
                default="scheduled_for_check",
                max_length=32,
            ),
        ),
    ]
