# Generated by Django 4.2.11 on 2024-05-14 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_event_is_marked_spam_job_is_marked_spam_spamcontent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="spamcontent",
            name="detection_details",
            field=models.JSONField(
                default=dict,
                help_text="Extra context from the detection method, e.g. NLP results, elapsed time",
            ),
        ),
        migrations.AddField(
            model_name="spamcontent",
            name="detection_method",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="spamcontent",
            name="review_notes",
            field=models.TextField(
                blank=True, help_text="Additional notes left by the reviewer", null=True
            ),
        ),
    ]
