# Generated by Django 3.2.19 on 2023-06-06 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_memberprofile_industry'),
        ('curator', '0002_rename_tagcleanup_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpamRecommendation',
            fields=[
                ('member_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.memberprofile')),
                ('is_spam_labelled_by_classifier', models.BooleanField(default=False)),
                ('is_spam_labelled_by_curator', models.BooleanField(default=False)),
                ('is_labelled_by_curator_before', models.BooleanField(default=False)),
                ('classifier_confidence', models.FloatField(default=0)),
                ('last_updated_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
