# Generated by Django 3.2.19 on 2023-06-11 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_memberprofile_industry'),
        ('curator', '0002_rename_tagcleanup_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpamRecommendation',
            fields=[
                ('member_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.memberprofile')),
                ('labelled_by_bio_classifier', models.BooleanField(default=None, null=True)),
                ('bio_classifier_confidence', models.FloatField(default=0)),
                ('labelled_by_user_classifier', models.BooleanField(default=None, null=True)),
                ('user_classifier_confidence', models.FloatField(default=0)),
                ('labelled_by_curator', models.BooleanField(default=None, null=True)),
                ('date_updated', models.DateField(auto_now=True)),
            ],
        ),
    ]
