# Generated by Django 4.2.7 on 2024-04-10 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_alter_eventtag_tag_alter_jobtag_tag_and_more"),
        ("curator", "0003_canonicaltag_canonicaltagmapping_tagcluster"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSpamStatus",
            fields=[
                (
                    "member_profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="core.memberprofile",
                    ),
                ),
                ("label", models.BooleanField(default=None, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("is_training_data", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="UserSpamPrediction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("context_id", models.CharField(max_length=300)),
                ("prediction", models.BooleanField(default=False)),
                ("confidence", models.FloatField(default=0)),
                ("date_created", models.DateTimeField(auto_now=True)),
                (
                    "spam_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="curator.userspamstatus",
                    ),
                ),
            ],
        ),
    ]
