# Generated by Django 3.2.19 on 2023-06-08 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curator', '0003_spamrecommendation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spamrecommendation',
            name='is_labelled_by_curator_before',
        ),
        migrations.AlterField(
            model_name='spamrecommendation',
            name='is_spam_labelled_by_classifier',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='spamrecommendation',
            name='is_spam_labelled_by_curator',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
