# Generated by Django 3.2.19 on 2023-07-18 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_alter_memberprofile_industry"),
        ("curator", "0003_canonicaltag_canonicaltagmapping_tagcluster"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSpamStatus",
            fields=[
                (
                    "member_profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="core.memberprofile",
                    ),
                ),
                (
                    "labelled_by_text_classifier",
                    models.BooleanField(default=None, null=True),
                ),
                ("text_classifier_confidence", models.FloatField(default=0)),
                (
                    "labelled_by_user_classifier",
                    models.BooleanField(default=None, null=True),
                ),
                ("user_classifier_confidence", models.FloatField(default=0)),
                ("labelled_by_curator", models.BooleanField(default=None, null=True)),
                ("last_updated", models.DateField(auto_now=True)),
                ("is_training_data", models.BooleanField(default=False)),
            ],
        ),
    ]
