#!/bin/bash

# run standard django tests
docker-compose run --rm cms /code/deploy/test.sh
# run frontend tests
docker-compose up -d && docker-compose exec cms ./manage.py setup_frontend_tests && docker-compose exec js /code/deploy/test.sh
