name: Check Code Style/Lint [frontend-next]

on:
  push:
    branches: [ main ]
    paths: [ 'frontend-next/**' ]
  pull_request:
    branches: [ main ]
    paths: [ 'frontend-next/**' ]

jobs:

  check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend-next
    steps:
    - uses: actions/checkout@v3

    - name: Set up node
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'yarn'

    - name: Clean install
      run: yarn install --frozen-lockfile

    - name: Lint
      run: yarn lint

    - name: Check formatting
      # run regardless of whether linting caught errors
      if: ${{ success() || failure() }}
      run: yarn style
