name: Check Code Style/Lint [Vue/TS]

on:
  push:
    branches: [ main ]
    paths: [ 'frontend/**' ]
  pull_request:
    branches: [ main ]
    paths: [ 'frontend/**' ]

jobs:

  check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
    - uses: actions/checkout@v3
    - name: Set up node
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: Clean install
      run: yarn config set ignore-engines true && yarn install --frozen-lockfile
    - name: Lint
      run: yarn lint
    - name: Check formatting
      # run regardless of whether linting caught errors
      if: ${{ success() || failure() }}
      run: yarn style
