name: Django CI

on:
  push:
    branches: [ vue3 ]
  pull_request:
    branches: [ vue3 ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: build containers and run Django tests
      run: make test
